; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-atoms3]
; ★ espressif32@6.7.0 (Arduino Core v2) に戻す
;    pioarduino 55.03.36 (Core v3) では ledcAttach 直後のグリッチでサーボが跳ねる問題が解消できなかったため。
platform = espressif32@6.7.0
board = m5stack-atoms3
framework = arduino
board_build.partitions = max_app_8MB.csv     ; for AtomS3/R
board_build.arduino.memory_type = qio_opi    ; PSRAM for AtomS3R
; board_build.f_flash = 80000000L
; board_build.f_cpu = 240000000L
upload_speed = 115200
monitor_speed = 115200
upload_flags =
  --no-stub
lib_deps = 
  m5stack/M5Unified @ ^0.2.8
  bblanchon/ArduinoJson @ ^6
  ESP32WebServer ; Add for Web Setting

build_flags =
;    -DCORE_DEBUG_LEVEL=4
    -DCORE_DEBUG_LEVEL=2
    -DBOARD_HAS_PSRAM    ; PSRAM(ON) for AtomS3R
    -DARDUINO_USB_MODE=1 ; USB CDCモード
    -DARDUINO_USB_CDC_ON_BOOT=1 ; USB CDCモードをON
    -DENABLE_SERVO
; Set com port if you need
; upload_port = COM8
